remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Kobe's Portfolio"
email: "kbarre05@uoguelph.ca"
phone: "705-221-1186"
phone_icon: <img src="https://githerdone17.github.io/kobes-portfolio/Images/Phone_icon.jpg" alt="drawing" width="20"/>
